FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y shellinabox && \
    rm -rf /var/lib/apt/lists/*

# Set a strong password for root (using environment variable for security)
ENV ROOT_PASSWORD your_strong_password 
RUN usermod -p $(openssl passwd "$ROOT_PASSWORD" | cut -d ':' -f 2) root

EXPOSE 22

CMD ["/usr/bin/shellinaboxd","-t","-s","/:LOGIN"]
